# Register all versions so user can choose
from .universal_llm_prompt_node import NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_V1, NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_V1
from .universal_llm_prompt_node_v2 import NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_V2, NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_V2
from .universal_llm_prompt_node_v4 import NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_V4, NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_V4
from .comfyui_dual_vllm import NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_V5, NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_V5
from .test_image_formats import NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_TEST, NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_TEST

# Merge all versions
NODE_CLASS_MAPPINGS = {
    **NODE_CLASS_MAPPINGS_V1,
    **NODE_CLASS_MAPPINGS_V2,
    **NODE_CLASS_MAPPINGS_V4,
    **NODE_CLASS_MAPPINGS_V5,
    **NODE_CLASS_MAPPINGS_TEST
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **NODE_DISPLAY_NAME_MAPPINGS_V1,
    **NODE_DISPLAY_NAME_MAPPINGS_V2,
    **NODE_DISPLAY_NAME_MAPPINGS_V4,
    **NODE_DISPLAY_NAME_MAPPINGS_V5,
    **NODE_DISPLAY_NAME_MAPPINGS_TEST
}

# Explicit exports for ComfyUI
__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']

# Debug print
print(f"[UniversalLLM __init__] Registered {len(NODE_CLASS_MAPPINGS)} node(s):")
for node_name in NODE_DISPLAY_NAME_MAPPINGS.values():
    print(f"  - {node_name}")


